/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:dea304c0-55e2-4c4d-8d27-601151c79a55",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_dk3nI2GwP",
    "aws_user_pools_web_client_id": "5qsjnilaphjcd3bske1ff1bql",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://wmow66nvpvgipjkwyugav4xoye.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-l4lewvu2hfhqnd3swm7yobhh6q",
    "aws_user_files_s3_bucket": "awsamplify956b7a97cc374a71837747342c35b387233250-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
